export default {
    ADD_PRICE: 'ADD_PRICE',
    SUBTRACT_PRICE: 'SUBTRACT_PRICE',
    GET_INGREDIENTS: 'GET_INGREDIENTS',
    SET_INGREDIENTS: 'SET_INGREDIENTS',
    INC_INGREDIENT: 'INC_INGREDIENT',
    DEC_INGREDIENT: 'DEC_INGREDIENT',
    RESET_INGREDIENTS: 'RESET_INGREDIENTS',
    SET_INITIAL_PRICE: 'SET_INITIAL_PRICE',
    SET_TOTAL_PRICE: 'SET_TOTAL_PRICE',
}